apiVersion: v1
kind: Service
metadata:
  name: redis01
  labels:
    app: redis01
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis01
---
apiVersion: v1
kind: Service
metadata:
  name: redis02
  labels:
    app: redis02
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis02