kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis01-pvc
  labels:
    app: redis01-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis02-pvc
  labels:
    app: redis02-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis01
  labels:
    app: redis01
spec:
  selector:
    matchLabels:
        app: redis01
  template:
    metadata:
      labels:
        app: redis01
    spec:
      containers:
      - name: redis01
        image: redis:6.2.3-alpine
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        volumeMounts:
        - name: "redis-conf"
          mountPath: "/etc/redis"
        - name: "redis-data"
          mountPath: "/var/lib/redis"
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
            claimName: redis01-pvc
        - name: "redis-conf"
          configMap:
            name: "redis-conf"
            items:
              - key: "redis.conf"
                path: "redis.conf"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis02
  labels:
    app: redis02
spec:
  selector:
    matchLabels:
        app: redis02
  template:
    metadata:
      labels:
        app: redis02
    spec:
      containers:
      - name: redis02
        image: redis:6.2.3-alpine
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        volumeMounts:
        - name: "redis-conf"
          mountPath: "/etc/redis"
        - name: "redis-data"
          mountPath: "/var/lib/redis"
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
            claimName: redis02-pvc
        - name: "redis-conf"
          configMap:
            name: "redis-conf"
            items:
              - key: "redis.conf"
                path: "redis.conf"